---
schema_version: "1"
timestamp: "2025-10-24T10:24:53-07:00"
context:
    problem_statement: Implementing two-tier context system to maintain LLM development continuity
    key_insights:
        - insight: Context discontinuity is the primary challenge in LLM-assisted development
          impact: Capturing 'why' decisions were made enables effective session resumption and consistent decision-making
          scope: project
        - insight: Two-tier context (point-in-time + project-wide) manages LLM context window size
          impact: Project file stays small and focused while checkpoint context preserves full history
          scope: project
        - insight: Human curation is essential for project-level context quality
          impact: Automated aggregation would create noise; human judgment maintains signal
          scope: project
    decisions_made:
        - decision: Split context into checkpoint-specific and project-wide files
          rationale: Keeps LLM context manageable (project + recent entries) while preserving full historical detail
          alternatives_considered:
            - Single aggregated context file
            - Automated context summarization
          constraints_that_influenced: LLM context window limits and need for both detail and manageability
          scope: project
        - decision: Use append-only recommendations queue in project file
          rationale: Avoids automation complexity while providing helpful suggestions that human can review and incorporate
          alternatives_considered:
            - Automated merging of project-scoped items
            - Separate recommendations file
          constraints_that_influenced: Human responsibility for curation quality, need for simple workflow
          scope: project
        - decision: Include commit_hash in context entries for linking
          rationale: Allows correlation between context, changelog, and git history
          scope: checkpoint
        - decision: Pre-populate all project document fields with examples
          rationale: Provides clear structure and guidance for human curators
          scope: checkpoint
    established_patterns:
        - pattern: Multi-document YAML for consumption doc + recommendation queue
          rationale: First document stays clean for LLM consumption, subsequent docs provide curation suggestions
          examples: .checkpoint-project.yml structure with main doc followed by recommendations per checkpoint
          scope: project
        - pattern: Context items marked with scope field to indicate checkpoint vs project applicability
          rationale: Enables automatic extraction of project-level recommendations while keeping checkpoint-specific details separate
          examples: key_insights, decisions_made, failed_approaches, established_patterns all support scope field
          scope: project
    conversation_context:
        - exchange: Discussed whether context belongs in changelog or separate file - decided separate
          outcome: Context has different lifecycle and consumption pattern than changelog; separation maintains clarity
        - exchange: Questioned whether to automate project file updates - decided against
          outcome: Human curation is essential for quality; tool provides recommendations as queue for review
        - exchange: Debated context file format and line length restrictions
          outcome: Context uses .yml extension with relaxed line lengths for detailed explanations
        - exchange: Identified that language detection belongs in meta document as project characteristic
          outcome: Led to understanding that some context is project-level, some is checkpoint-level
---
schema_version: "1"
timestamp: "2025-10-24T10:57:48-07:00"
context:
    problem_statement: Completing project schema with comprehensive structured fields and fixing context correlation mechanism
    key_insights:
        - insight: Commit hash is only needed in changelog, not context or project files
          impact: Simplifies correlation model - timestamp alone links entries across all files
          scope: project
        - insight: Comprehensive project schema enables complete project understanding
          impact: 'All aspects of project captured: dependencies, targets, testing, roles, constraints'
          scope: project
        - insight: Explicit examples in templates guide LLM behavior effectively
          impact: Inline examples prevent confusion about checkpoint vs project scope
          scope: project
    decisions_made:
        - decision: Use timestamp-only correlation instead of backfilling hashes to multiple files
          rationale: Only changelog participates in git commit, so only it needs the hash; timestamp is sufficient for linking across files
          alternatives_considered:
            - Backfill commit hash to all three files
            - Use ULID or other correlation ID
          constraints_that_influenced: Context and project files don't stage/commit with changelog, making hash backfill complex
          scope: project
        - decision: Add all 10 new schema sections in single checkpoint
          rationale: Complete schema provides full project characterization; partial implementation would leave gaps
          alternatives_considered:
            - Implement sections incrementally
            - Wait to see which sections are actually needed
          constraints_that_influenced: Schema should be comprehensive from the start for LLM understanding
          scope: checkpoint
        - decision: Backport complete schema to existing project file
          rationale: Existing project file should demonstrate the full schema with real checkpoint-specific values
          scope: checkpoint
    failed_approaches:
        - approach: Initially included commit_hash in context entries
          why_failed: Unnecessary complexity - only changelog needs hash since it's the only file staged/committed
          lessons_learned: Correlation mechanism should match the actual workflow, not add unnecessary fields
          scope: project
    established_patterns:
        - pattern: Comprehensive structured schemas with inline examples in templates
          rationale: Reduces LLM confusion by providing explicit guidance and examples for each field
          examples: Context template now includes examples of checkpoint vs project scope for each field type
          scope: project
        - pattern: Timestamp-based correlation across append-only files
          rationale: Single source of truth (timestamp) links entries without complex backfill mechanisms
          examples: Changelog, context, and project files all use matching timestamps to correlate entries
          scope: project
    conversation_context:
        - exchange: Identified that commit_hash was incorrectly added to context entries
          outcome: Removed hash from context schema and eliminated backfill code - only changelog needs it
        - exchange: Discussed which project schema sections are most valuable
          outcome: Implemented all 10 suggested sections for comprehensive project characterization
        - exchange: Questioned whether LLM would understand new fields without context
          outcome: Added detailed instructions, complete section list, and inline examples to context template
        - exchange: Considered whether to backport new schema to existing project file
          outcome: Updated existing file with all new fields and checkpoint-specific real values
---
schema_version: "1"
timestamp: "2025-10-28T13:04:19-07:00"
context:
    problem_statement: LLM incorrectly attempted to run 'checkpoint check' before implementing any code changes, revealing missing workflow guidance for session start
    key_insights:
        - insight: Workflow needs explicit session entry point that validates state and guides next steps
          impact: Prevents confusion about when to run which command; makes workflow self-teaching
          scope: project
        - insight: Commands that call os.Exit are hard to test
          impact: Extract testable internal implementation that returns success/failure bool
          scope: project
    decisions_made:
        - decision: Create 'start' command as first command of each work session
          rationale: Validates readiness (git repo, checkpoint init, no conflicts), shows context (next steps), guides user to next action
          alternatives_considered:
            - Add --status flag to check command
            - Just improve documentation
          constraints_that_influenced: Need to catch workflow errors early; documentation alone isn't enough for LLMs
          scope: project
        - decision: Show warnings but don't fail on non-critical issues
          rationale: Pending recommendations or changes in working directory shouldn't block starting work
          alternatives_considered:
            - Fail on any non-clean state
          scope: checkpoint
    failed_approaches:
        - approach: Initially tried to mock os.Exit in tests
          why_failed: Mock approach is fragile and doesn't test actual behavior
          lessons_learned: Better pattern is public wrapper that calls testable internal implementation
          scope: project
    established_patterns:
        - pattern: Commands should have both public wrapper and testable internal implementation
          rationale: Allows comprehensive testing without mocking os.Exit or other system calls
          examples: Start() calls startInternal() which returns bool; same pattern should apply to other commands that call os.Exit
          scope: project
        - pattern: Start command as session entry point
          rationale: Validates state, shows context, guides next action - makes workflow explicit
          examples: Run 'checkpoint start' at beginning of each work session
          scope: project
    conversation_context:
        - exchange: User correctly identified that I misunderstood the workflow by running 'checkpoint check' before doing any work
          outcome: Realized need for explicit 'start' command that validates readiness and explains what to do. This is Checkpoint 0 - improving the workflow itself.
        - exchange: Discussed whether to fail on warnings (in-progress checkpoint, pending recommendations)
          outcome: Decided warnings shouldn't block start - they're informational. Only errors (no git, no init) should prevent starting work.
        - exchange: Question about how to count checkpoints in changelog
          outcome: Realized document separators (---) are the correct approach; first separator marks meta doc, subsequent ones mark checkpoints
---
schema_version: "1"
timestamp: "2025-10-28T13:31:04-07:00"
context:
    problem_statement: Input file was too large (460+ lines) due to embedded project context and recent context, making it difficult to edit and causing tool failures. Also needed to establish organized directory structure for supporting materials per Checkpoint 1 plan.
    key_insights:
        - insight: Input file should be minimal and focused on what needs to be filled
          impact: Keeps input file manageable (~170 lines vs 460+), easier to edit, prevents tool failures. LLM can read source files directly when needed.
          scope: project
        - insight: Supporting materials need organized structure separate from root
          impact: Clean separation between data files (root) and documentation/examples (.checkpoint/ directory)
          scope: project
    decisions_made:
        - decision: Remove project_context, recent_context, and languages from input template
          rationale: These are reference materials that bloat the file but aren't used by commit. LLM can read .checkpoint-project.yml and .checkpoint-context.yml directly when filling input.
          alternatives_considered:
            - Keep embedded but compress/summarize
            - Move to separate reference file that check creates
          constraints_that_influenced: Edit tool struggled with 460+ line files; human user found it unwieldy
          scope: project
        - decision: Create .checkpoint/ directory with subdirectories in init command
          rationale: Provides organized location for examples, guides, prompts, and templates. Tracked in git so structure is preserved.
          alternatives_considered:
            - Flat .checkpoint/ directory
            - Multiple top-level dot directories
          constraints_that_influenced: Need clean root directory; examples and guides need logical organization
          scope: checkpoint
    established_patterns:
        - pattern: Reference files by path in comments rather than embedding content
          rationale: Keeps files focused and manageable; users/LLMs can read full files when needed
          examples: Input template now has comments pointing to .checkpoint-project.yml and .checkpoint-context.yml
          scope: project
    conversation_context:
        - exchange: User questioned why project context was in input file and whether it was needed at commit time
          outcome: Realized project context was only reference material for filling, not used by commit. Led to removing all embedded reference material.
        - exchange: User noticed edit tool had difficulty with the large input file
          outcome: Confirmed that 460+ line input file was problematic; reduced to ~170 lines by removing embedded contexts
